### ISSUE TITLE
New Pimpkin Boss

### ISSUE THREAD

**Issue by George540** [The-GameDJs/CostumeCurse#151]
New Pimpkin Boss implementation for the final release of the game. Old boss was just a placeholder for years that did not add any interest or fun to the game. This new update is made for it.

- [x] - New Boss Model
- [x] - Model Texturing
- [x] - Idle Animation
- [x] - Bonk Animation
- [x] - Hurt Animation
- [x] - Death Animation
- [x] - Thrust Animation
- [x] - Throw Animation
- [x] - Summon Animation
- [x] - Import Boss FBX into Unity
- [x] - Create and integrate Cursed Boss Prefab
- [x] - Implement Bonk Ability
- [x] - Implement Firecharge Ability
- [x] - Implement new Fire VFX
- [x] - Implement Candy Storm
- [x] - Implement Candy Storm Boss UI event
- [x] - Implement Dark Pimpkin Variant
- [x] - Integrate new Final Battle
- [x] - Fix Boss Animation Snags
- [x] - Fix Pimpkin Minion issues
- [x] - Implement new abilities SFX
- [x] - Implement Boss character SFX
- [x] - Polish Boss environment and village
- [x] - Finish Death Sequence
- [x] - Test Gameplay Support
