### ISSUE TITLE
Ending Sequence

### ISSUE THREAD

**Issue by George540** [The-GameDJs/CostumeCurse#152]
Ending sequence was always buggy and lacked substance. In relation to the boss, create ending sequence of the game to finish it once and for all!

- [x] - Boss Death Camera Shake, Flash and SFX
- [x] - Epilogue Scene (early morning of prologue)
- [x] - Create automatic final emotional dialogue
- [x] - Hint new Costume Curse game 👀
